url: "https://numerik-ea.github.io"
baseurl: "/composants/"

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store
  - switch_gemfile.sh
  - switch_gemfile.ps1
  - LICENSE